### ISSUE TITLE
使用自带的数据都报错

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#424]
---
due: 2021-08-10
---

Contact: Feng Jiang / dxyjiang@163.com
Tool: gene density
使用自带的数据都报错，望解决

**Comment by ShixiangWang** [comment]
确定是一个 bug。

```
[1] "Chr5"  "Chr8"  "Chr9"  "Chr10" "Chr12"
ERROR [2021-08-04 16:52:34] Error in names(sector.data) <- colnames(.SECTOR.DATA)[-1]: 'names' attribute [6] must be the same length as the vector [0]

```

@dongwei1220 有空解决下？

**Comment by dongwei1220** [comment]
诗翔，那个我看了github上绘图的原始代码是没有问题的，这个报错信息我这里看不出来是从哪里来的。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "hiplot/gold"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiplot/gold] 使用自带的数据都报错 (#424)





 
确定是一个 bug。
 [1] "Chr5"  "Chr8"  "Chr9"  "Chr10" "Chr12" ERROR [2021-08-04 16:52:34] Error in names(sector.data) <- colnames(.SECTOR.DATA)[-1]: 'names' attribute [6] must be the same length as the vector [0]  
@dongwei1220 有空解决下？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShixiangWang** [comment]
这个就是默认示例运行就会报错

**Comment by Miachol** [comment]
有可能是 Plumber 运行环境的问题


--------------原始邮件--------------
发件人："Shixiang Wang ***@***.***&gt;;
发送时间：2021年8月4日(星期三) 下午5:39
收件人："hiplot/gold" ***@***.***&gt;;
抄送："Jianfeng ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [hiplot/gold] 使用自带的数据都报错 (#424)
-----------------------------------

 

 
这个就是默认示例运行就会报错
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShixiangWang** [comment]
@Miachol  前段时间也是 plumber 的问题？能不能中间插入一段代码，检测可能的异常？
